config/routes.rb
RailsTest::Application.routes.draw do
  resources :permission_assocs

  resources :permissions

  resources :users

end

app/models/permission.rb
class Permission < ActiveRecord::Base
  attr_accessible :name, :user_id
  belongs_to :user
  
  validates :name, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :permissions_attributes
  has_many :permissions
  validates_associated :permissions
  accepts_nested_attributes_for :permissions, :allow_destroy => true, :reject_if => :all_blank
  validates :name, :presence => true    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/permissions_controller.rb
class PermissionsController < ApplicationController
  # GET /permissions
  # GET /permissions.json
  def index
    @permissions = Permission.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @permissions }
    end
  end

  # GET /permissions/1
  # GET /permissions/1.json
  def show
    @permission = Permission.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @permission }
    end
  end

  # GET /permissions/new
  # GET /permissions/new.json
  def new
    @permission = Permission.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @permission }
    end
  end

  # GET /permissions/1/edit
  def edit
    @permission = Permission.find(params[:id])
  end

  # POST /permissions
  # POST /permissions.json
  def create
    @permission = Permission.new(params[:permission])

    respond_to do |format|
      if @permission.save
        format.html { redirect_to @permission, :notice => 'Permission was successfully created.' }
        format.json { render :json => @permission, :status => :created, :location => @permission }
      else
        format.html { render :action => "new" }
        format.json { render :json => @permission.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /permissions/1
  # PUT /permissions/1.json
  def update
    @permission = Permission.find(params[:id])

    respond_to do |format|
      if @permission.update_attributes(params[:permission])
        format.html { redirect_to @permission, :notice => 'Permission was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @permission.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /permissions/1
  # DELETE /permissions/1.json
  def destroy
    @permission = Permission.find(params[:id])
    @permission.destroy

    respond_to do |format|
      format.html { redirect_to permissions_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    edit
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    render :edit    
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    @user.permissions << Permission.new
    @user.permissions << Permission.new    
    render :edit    
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    if @user.save
      render :edit
    else
      render :action => "new" 
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      redirect_to @user, :notice => 'User was successfully updated.'
    else
      puts "some errors"
      render :edit
    end
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/permissions/_form.html.erb
<%= form_for(@permission) do |f| %>
  <% if @permission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@permission.errors.count, "error") %> prohibited this permission from being saved:</h2>

      <ul>
      <% @permission.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>


  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/permissions/edit.html.erb
<h1>Editing permission</h1>

<%= render 'form' %>

<%= link_to 'Show', @permission %> |
<%= link_to 'Back', permissions_path %>

app/views/permissions/index.html.erb
<h1>Listing permissions</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @permissions.each do |permission| %>
  <tr>
    <td><%= permission.name %></td>
    <td><%= link_to 'Show', permission %></td>
    <td><%= link_to 'Edit', edit_permission_path(permission) %></td>
    <td><%= link_to 'Destroy', permission, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Permission', new_permission_path %>

app/views/permissions/new.html.erb
<h1>New permission</h1>

<%= render 'form' %>

<%= link_to 'Back', permissions_path %>

app/views/permissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @permission.name %>
</p>


<%= link_to 'Edit', edit_permission_path(@permission) %> |
<%= link_to 'Back', permissions_path %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
  <%= f.fields_for :permissions do | fp | %>     
    <div class="field">
      <%= fp.label "permission_name" %><br />
      <%= fp.text_field :name %>
      <%= fp.check_box '_destroy' %> löschen
    </div>
  <% end %>


 
    <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>